### ISSUE TITLE
Bug - Players receiving gold

### ISSUE THREAD

**Issue by bkmangx1** [noisiver/mod-guildfunds#1]
Hey, I found a bug with this module. When `GuildFunds.Quests` is enabled and player completes a quest that requires gold payment, for example [An Earnest Proposition](https://www.wowhead.com/classic/quest=8917/an-earnest-proposition) their gold gets set to 4294 and same amount also added to guildbank.

**Comment by noisiver** [comment]
Thank you for bringing this to my attention! <3

It should be fixed now. I obviously forgot to test quests that require money when I was developing it. I've tested both the quest you linked and quests that reward money and it should work just fine. Please do tell me if there are still issues and I'll look at fixing it.

**Comment by bkmangx1** [comment]
Thanks for the update, I will report if I find any additional issues.
